# base image
FROM node:14-alpine as build

# set working directory
WORKDIR /app

# install app dependencies
COPY package*.json ./
RUN npm install

# add app
COPY . .

# build the app
RUN npm run build

# production environment
FROM node:14-alpine
WORKDIR /app
COPY --from=build /app/build ./
COPY package*.json ./
RUN npm install --only=production
EXPOSE 3000
CMD [ "npm", "start" ]
