# base image
FROM python:3.8-slim-buster

# set working directory
WORKDIR /app

# copy requirements file
COPY requirements.txt .
COPY ./Backend/main.py .
COPY ./Backend/SortMap.py .


# install dependencies
RUN pip3 install -r requirements.txt

# copy the rest of the application
COPY . .

# expose the port
EXPOSE 8000

# run the command to start the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
